# Generated by Django 2.2.5 on 2022-09-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20220705_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(default='in stock', max_length=10, null=True),
        ),
    ]
